server:
  port: 8088
spring:
  application:
    name: config-sever

  cloud:
    config:
      server:
        git:
          uri: https://github.com/vivekshri1/micro-service-configuration
          clone-on-start: true